apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: false
    url: postgres:5432
    database: {{POSTGRES_DB}}
    user: admin
    secureJsonData:
      password: {{POSTGRES_PW}}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false