{
 "title": "SentinelOne KPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total threats in the last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"total_threats\")\n    |> yield()"
    }
   ]
  },
  {
   "title": "Resolved threats in the last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"resolved_threats\")\n    |> yield()"
    }
   ]
  },
  {
   "title": "Resolved FP threats in the last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"resolved_threats_fp\")\n    |> yield()"
    }
   ]
  },
  {
   "title": "Resolved TP threats in the last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"resolved_threats_tp\")\n    |> yield()"
    }
   ]
  }
 ]
}